name: Terraform Deployment

on:
  push:
    branches:
      - staging
    tags:
      - 'v*.*.*'

permissions:
  contents: read

jobs:
  terraform:
    name: Deploy Infraestrutura com Terragrunt
    runs-on: ubuntu-latest

    steps:
      - name: Checkout do código
        uses: actions/checkout@v4

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.11.4

      - name: Instalar Terragrunt
        run: |
          curl -L -o terragrunt https://github.com/gruntwork-io/terragrunt/releases/download/v0.57.4/terragrunt_linux_amd64
          chmod +x terragrunt
          sudo mv terragrunt /usr/local/bin/

      - name: Authenticate to GCP
        uses: google-github-actions/auth@v2
        with:
          credentials_json: ${{ secrets.GCP_CREDENTIALS }}
          create_credentials_file: true

      - name: Inicializar Terragrunt
        working-directory: terraform/terragrunt/gke
        run: terragrunt init
        env:
          GOOGLE_APPLICATION_CREDENTIALS: ${{ env.GOOGLE_GHA_CREDS_PATH }}
    
      - name: Executar Terragrunt Plan
        if: github.ref == 'refs/heads/staging'
        working-directory: terraform/terragrunt/gke
        run: terragrunt plan

      - name: Aplicar Infraestrutura
        if: startsWith(github.ref, 'refs/tags/')
        working-directory: terraform/terragrunt/gke
        run: terragrunt apply -auto-approve